import AppKit
import UniformTypeIdentifiers
import TreeCore

/// Real `NSPasteboard.general` adapter. Stateless (uses the global pasteboard),
/// so it satisfies `PasteboardSource: Sendable`. This is the only file that
/// touches AppKit's pasteboard; everything downstream is UI-free TreeCore.
public struct SystemPasteboardSource: PasteboardSource {
    public init() {}

    public var changeCount: Int { NSPasteboard.general.changeCount }

    public func snapshot() -> RawSnapshot? {
        let pb = NSPasteboard.general
        guard let items = pb.pasteboardItems, !items.isEmpty else { return nil }

        var flags: CaptureFlags = []
        let present = Set((pb.types ?? []).map(\.rawValue))
        if present.contains("org.nspasteboard.ConcealedType") { flags.insert(.concealed) }
        if present.contains("org.nspasteboard.TransientType") { flags.insert(.transient) }
        if present.contains("org.nspasteboard.AutoGeneratedType") { flags.insert(.autoGenerated) }

        // Concealed content: don't even read the bytes.
        if flags.contains(.concealed) {
            return RawSnapshot(changeCount: pb.changeCount, representations: [], flags: flags,
                               sourceApp: Self.frontmostBundleID())
        }

        var reps: [Representation] = []
        for item in items {
            let itemTypes = item.types.map(\.rawValue)
            // Skip the redundant, huge TIFF when a PNG is also offered — avoids
            // reading tens of MB just to discard it in the planner (§3.5).
            let hasPNG = itemTypes.contains("public.png")
            for type in item.types {
                let uti = type.rawValue
                if uti == "public.tiff" && hasPNG { continue }
                guard let data = item.data(forType: type) else { continue }
                reps.append(Representation(uti: uti, bytes: data, isImage: Self.isImage(uti)))
            }
        }
        guard !reps.isEmpty else { return nil }
        return RawSnapshot(changeCount: pb.changeCount, representations: reps, flags: flags,
                           sourceApp: Self.frontmostBundleID())
    }

    static func isImage(_ uti: String) -> Bool {
        UTType(uti)?.conforms(to: .image) ?? false
    }

    static func frontmostBundleID() -> String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }
}
