import Foundation

/// Pasteboard hint types that gate capture. These map to the well-known
/// `org.nspasteboard.*` conventions that password managers and transient
/// producers set (design §4). TreeCore stays AppKit-free: the capture adapter
/// (TreeCapture) translates real pasteboard types into these flags.
public struct CaptureFlags: OptionSet, Sendable {
    public let rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }

    /// `org.nspasteboard.TransientType` — content not meant to be retained.
    public static let transient = CaptureFlags(rawValue: 1 << 0)
    /// `org.nspasteboard.ConcealedType` — passwords/secrets. Never stored.
    public static let concealed = CaptureFlags(rawValue: 1 << 1)
    /// `org.nspasteboard.AutoGeneratedType` — machine-generated, skip.
    public static let autoGenerated = CaptureFlags(rawValue: 1 << 2)
}
