import Foundation

/// What to do with a pasteboard change. Pure decision; no side effects.
public enum FilterDecision: Equatable, Sendable {
    case capture
    case ignore(reason: String)
}

public struct FilterConfig: Sendable {
    /// Bundle ids whose copies are never captured (e.g. password managers).
    public var ignoredApps: Set<String>
    /// Drop empty snapshots. Deliberately no *upper* bound — long text is the
    /// whole point (agent @file channel), unlike PasteBar's 5000-char cutoff.
    public var minBytes: Int

    public init(ignoredApps: Set<String> = [], minBytes: Int = 1) {
        self.ignoredApps = ignoredApps
        self.minBytes = minBytes
    }
}

/// Ordered ignore rules (design §4). Concealed is checked first and hardest:
/// treeclip must never persist a password even transiently.
public enum FilterChain {
    public static func decide(
        flags: CaptureFlags, sourceApp: String?, totalBytes: Int, config: FilterConfig
    ) -> FilterDecision {
        if flags.contains(.concealed) { return .ignore(reason: "concealed") }
        if flags.contains(.transient) { return .ignore(reason: "transient") }
        if flags.contains(.autoGenerated) { return .ignore(reason: "autoGenerated") }
        if let app = sourceApp, config.ignoredApps.contains(app) {
            return .ignore(reason: "ignoredApp:\(app)")
        }
        if totalBytes < config.minBytes { return .ignore(reason: "empty") }
        return .capture
    }
}
