import Foundation

/// What to do with a pasteboard change. Pure decision; no side effects.
public enum FilterDecision: Equatable, Sendable {
    case capture
    case ignore(reason: String)
}

public struct FilterConfig: Sendable {
    /// Bundle ids whose copies are never captured (e.g. password managers).
    public var ignoredApps: Set<String>
    /// Pasteboard UTIs whose presence suppresses capture — the robust way to
    /// respect password/snippet managers that stamp their own type (1Password,
    /// KeeWeb, TypeIt4Me…), beyond the org.nspasteboard.* flags.
    public var ignoredTypes: Set<String>
    /// If set and the plain text matches, the snapshot is ignored (user regex).
    public var ignoreRegex: String?
    /// Drop empty snapshots. Deliberately no *upper* bound — long text is the
    /// whole point (agent @file channel), unlike PasteBar's 5000-char cutoff.
    public var minBytes: Int

    public init(ignoredApps: Set<String> = [], ignoredTypes: Set<String> = [],
                ignoreRegex: String? = nil, minBytes: Int = 1) {
        self.ignoredApps = ignoredApps
        self.ignoredTypes = ignoredTypes
        self.ignoreRegex = ignoreRegex
        self.minBytes = minBytes
    }
}

/// Ordered ignore rules (design §4). Concealed is checked first and hardest:
/// treeclip must never persist a password even transiently.
public enum FilterChain {
    public static func decide(
        flags: CaptureFlags, sourceApp: String?, presentUTIs: Set<String>,
        text: String?, totalBytes: Int, config: FilterConfig
    ) -> FilterDecision {
        if flags.contains(.concealed) { return .ignore(reason: "concealed") }
        if flags.contains(.transient) { return .ignore(reason: "transient") }
        if flags.contains(.autoGenerated) { return .ignore(reason: "autoGenerated") }
        if let app = sourceApp, config.ignoredApps.contains(app) {
            return .ignore(reason: "ignoredApp:\(app)")
        }
        if !config.ignoredTypes.isDisjoint(with: presentUTIs) {
            return .ignore(reason: "ignoredType")
        }
        if let pattern = config.ignoreRegex, let text, matchesRegex(text, pattern) {
            return .ignore(reason: "regex")
        }
        if totalBytes < config.minBytes { return .ignore(reason: "empty") }
        return .capture
    }

    static func matchesRegex(_ text: String, _ pattern: String) -> Bool {
        guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
        return re.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)) != nil
    }
}
