import Testing
import Foundation
@testable import TreeCore

@Suite struct FilterChainTests {
    let cfg = FilterConfig(ignoredApps: ["com.1password.1password"], minBytes: 1)

    private func decide(_ flags: CaptureFlags = [], app: String? = nil, bytes: Int = 100) -> FilterDecision {
        FilterChain.decide(flags: flags, sourceApp: app, presentUTIs: [], text: nil,
                           totalBytes: bytes, config: cfg)
    }

    @Test func concealedIsNeverStored() {
        #expect(decide(.concealed) == .ignore(reason: "concealed"))
    }

    @Test func transientAndAutoGeneratedIgnored() {
        #expect(decide(.transient) == .ignore(reason: "transient"))
        #expect(decide(.autoGenerated) == .ignore(reason: "autoGenerated"))
    }

    @Test func ignoredAppIsSkipped() {
        #expect(decide(app: "com.1password.1password")
                == .ignore(reason: "ignoredApp:com.1password.1password"))
    }

    @Test func emptyIsIgnoredButLongTextIsNot() {
        #expect(decide(bytes: 0) == .ignore(reason: "empty"))
        // No upper bound: a megabyte of text still captures.
        #expect(decide(app: "com.apple.Terminal", bytes: 1_000_000) == .capture)
    }
}

@Suite struct RepresentationPlannerTests {
    @Test func imagePrefersPngAndKeepsOne() {
        let plan = RepresentationPlanner.plan([
            RawRepresentation(uti: "public.tiff", byteCount: 5_000_000, isImage: true),
            RawRepresentation(uti: "public.png", byteCount: 200_000, isImage: true),
        ])
        #expect(plan.kind == "image")
        #expect(plan.keptUTIs == ["public.png"])          // redundant TIFF dropped
        #expect(plan.canonicalImageUTI == "public.png")
    }

    @Test func textKeepsPlainPlusRich() {
        let plan = RepresentationPlanner.plan([
            RawRepresentation(uti: "public.utf8-plain-text", byteCount: 20, isImage: false),
            RawRepresentation(uti: "public.rtf", byteCount: 80, isImage: false),
        ])
        #expect(plan.kind == "text")
        #expect(plan.keptUTIs == ["public.utf8-plain-text", "public.rtf"])
    }
}

@Suite struct ThumbnailSizingTests {
    @Test func capsLongEdgeAndPreservesAspect() {
        let t = ThumbnailSizing.target(width: 4000, height: 2000)
        #expect(t.w == 400)
        #expect(t.h == 200)
    }
    @Test func doesNotUpscaleSmallImages() {
        let t = ThumbnailSizing.target(width: 120, height: 80)
        #expect(t == (120, 80))
    }
}

@Suite struct ContentHashingTests {
    @Test func orderIndependentAndStable() {
        let a = ContentHashing.hash([("public.png", Data([1, 2, 3])), ("public.rtf", Data([9]))])
        let b = ContentHashing.hash([("public.rtf", Data([9])), ("public.png", Data([1, 2, 3]))])
        #expect(a == b)                                   // order independent
        #expect(a.count == 64)                            // sha256 hex
    }
    @Test func differsOnDifferentBytes() {
        let a = ContentHashing.hash([("public.utf8-plain-text", Data("hello".utf8))])
        let b = ContentHashing.hash([("public.utf8-plain-text", Data("world".utf8))])
        #expect(a != b)
    }
}
