import Testing
import Foundation
@testable import TreeCore

@Suite struct FilterChainTests {
    let cfg = FilterConfig(ignoredApps: ["com.1password.1password"], minBytes: 1)

    @Test func concealedIsNeverStored() {
        #expect(FilterChain.decide(flags: .concealed, sourceApp: nil, totalBytes: 100, config: cfg)
                == .ignore(reason: "concealed"))
    }

    @Test func transientAndAutoGeneratedIgnored() {
        #expect(FilterChain.decide(flags: .transient, sourceApp: nil, totalBytes: 100, config: cfg)
                == .ignore(reason: "transient"))
        #expect(FilterChain.decide(flags: .autoGenerated, sourceApp: nil, totalBytes: 100, config: cfg)
                == .ignore(reason: "autoGenerated"))
    }

    @Test func ignoredAppIsSkipped() {
        #expect(FilterChain.decide(flags: [], sourceApp: "com.1password.1password", totalBytes: 100, config: cfg)
                == .ignore(reason: "ignoredApp:com.1password.1password"))
    }

    @Test func emptyIsIgnoredButLongTextIsNot() {
        #expect(FilterChain.decide(flags: [], sourceApp: nil, totalBytes: 0, config: cfg)
                == .ignore(reason: "empty"))
        // No upper bound: a megabyte of text still captures.
        #expect(FilterChain.decide(flags: [], sourceApp: "com.apple.Terminal",
                                   totalBytes: 1_000_000, config: cfg) == .capture)
    }
}

@Suite struct RepresentationPlannerTests {
    @Test func imagePrefersPngAndKeepsOne() {
        let plan = RepresentationPlanner.plan([
            RawRepresentation(uti: "public.tiff", byteCount: 5_000_000, isImage: true),
            RawRepresentation(uti: "public.png", byteCount: 200_000, isImage: true),
        ])
        #expect(plan.kind == "image")
        #expect(plan.keptUTIs == ["public.png"])          // redundant TIFF dropped
        #expect(plan.canonicalImageUTI == "public.png")
    }

    @Test func textKeepsPlainPlusRich() {
        let plan = RepresentationPlanner.plan([
            RawRepresentation(uti: "public.utf8-plain-text", byteCount: 20, isImage: false),
            RawRepresentation(uti: "public.rtf", byteCount: 80, isImage: false),
        ])
        #expect(plan.kind == "text")
        #expect(plan.keptUTIs == ["public.utf8-plain-text", "public.rtf"])
    }
}

@Suite struct ThumbnailSizingTests {
    @Test func capsLongEdgeAndPreservesAspect() {
        let t = ThumbnailSizing.target(width: 4000, height: 2000)
        #expect(t.w == 400)
        #expect(t.h == 200)
    }
    @Test func doesNotUpscaleSmallImages() {
        let t = ThumbnailSizing.target(width: 120, height: 80)
        #expect(t == (120, 80))
    }
}

@Suite struct ContentHashingTests {
    @Test func orderIndependentAndStable() {
        let a = ContentHashing.hash([("public.png", Data([1, 2, 3])), ("public.rtf", Data([9]))])
        let b = ContentHashing.hash([("public.rtf", Data([9])), ("public.png", Data([1, 2, 3]))])
        #expect(a == b)                                   // order independent
        #expect(a.count == 64)                            // sha256 hex
    }
    @Test func differsOnDifferentBytes() {
        let a = ContentHashing.hash([("public.utf8-plain-text", Data("hello".utf8))])
        let b = ContentHashing.hash([("public.utf8-plain-text", Data("world".utf8))])
        #expect(a != b)
    }
}
